//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHR
    {
        public int id { get; set; }
        public string CourseCode { get; set; }
        public string TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string Discipline { get; set; }
        public string Venue { get; set; }
        public string Status { get; set; }
        public Nullable<int> LateIn { get; set; }
        public Nullable<int> LeftEarly { get; set; }
        public string Remarks { get; set; }
        public System.DateTime ClassDate { get; set; }
        public Nullable<int> sessionID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Session Session { get; set; }
    }
}
