//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeSessionKPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeSessionKPI()
        {
            this.KPIScore = new HashSet<KPIScore>();
        }
    
        public int id { get; set; }
        public Nullable<int> KPIID { get; set; }
        public Nullable<int> SubKPIID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual Session Session { get; set; }
        public virtual SubKPI SubKPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIScore> KPIScore { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
