//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.StudentEvaluation = new HashSet<StudentEvaluation>();
        }
    
        public int id { get; set; }
        public string studentID { get; set; }
        public string teacherID { get; set; }
        public string courseCode { get; set; }
        public Nullable<int> sessionID { get; set; }
        public string Section { get; set; }
        public string Grade { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentEvaluation> StudentEvaluation { get; set; }
    }
}
