//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIScore
    {
        public int id { get; set; }
        public Nullable<int> empKPIID { get; set; }
        public string empID { get; set; }
        public Nullable<int> score { get; set; }
        public string evaluatorID { get; set; }
        public Nullable<int> enrollmentID { get; set; }
        public string remarks { get; set; }
    
        public virtual EmployeSessionKPI EmployeSessionKPI { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Enrollment Enrollment { get; set; }
    }
}
