//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FYPEntities : DbContext
    {
        public FYPEntities()
            : base("name=FYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseAllocation> CourseAllocation { get; set; }
        public virtual DbSet<EmployeeType> EmployeeType { get; set; }
        public virtual DbSet<EmployeSessionKPI> EmployeSessionKPI { get; set; }
        public virtual DbSet<Enrollment> Enrollment { get; set; }
        public virtual DbSet<KPI> KPI { get; set; }
        public virtual DbSet<KPIScore> KPIScore { get; set; }
        public virtual DbSet<PeerEvaluation> PeerEvaluation { get; set; }
        public virtual DbSet<PeerEvaluator> PeerEvaluator { get; set; }
        public virtual DbSet<Questionare> Questionare { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentEvaluation> StudentEvaluation { get; set; }
        public virtual DbSet<SubKPI> SubKPI { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<SessionKPIWeight> SessionKPIWeight { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Societies> Societies { get; set; }
        public virtual DbSet<SocietyAssignments> SocietyAssignments { get; set; }
    }
}
