//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeerEvaluation
    {
        public int id { get; set; }
        public Nullable<int> evaluatorID { get; set; }
        public string evaluateeID { get; set; }
        public Nullable<int> questionID { get; set; }
        public string courseCode { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual PeerEvaluator PeerEvaluator { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Questionare Questionare { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
