//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int QuestionID { get; set; }
        public int QuestionareID { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual Questionare Questionare { get; set; }
    }
}
