//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyEvaluation
    {
        public int Id { get; set; }
        public string EvaluatorId { get; set; }
        public string EvaluateeId { get; set; }
        public int SocietyId { get; set; }
        public int QuestionId { get; set; }
        public int Score { get; set; }
        public int SessionId { get; set; }
        public string EvaluationType { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Session Session { get; set; }
        public virtual Societies Societies { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
