//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEvaluation
    {
        public int id { get; set; }
        public Nullable<int> enrollmentID { get; set; }
        public Nullable<int> questionID { get; set; }
        public Nullable<int> score { get; set; }
        public string StudentId { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual Student Student { get; set; }
    }
}
